# TASK

## TASK 1

In [33]:
# Import iris
from sklearn.datasets import load_iris

In [34]:
# Load the iris dataset.
df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')

In [35]:
# Load the dataset.
iris = load_iris()

What I understand from load_iris() is a function that load all the iris dataset to use it in future opportunities.

# TASK 2

In [36]:
# Display the shape of the dataset
print("Shape of the dataset:", X.shape)

Shape of the dataset: (150, 4)


In [53]:
# Display the first 5 rows of the data
print("First 5 rows of the data (features):")
print(X[:5])

First 5 rows of the data (features):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [52]:
# Display the last 5 rows of the data
print("Last 5 rows of the data (features):")
print(X[-5:])

Last 5 rows of the data (features):
[[6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


In [50]:
# Display feature names
print("Feature names:", iris.feature_names)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [51]:
# Display target names (target classes)
print("Target classes:", iris.target_names)

Target classes: ['setosa' 'versicolor' 'virginica']


## TASK 3

# Mean

In [45]:
# Calculates the mean of a numbers of a list.
import statistics

data1 = [1,2,3,4,5]

x = statistics.mean(data1)

print("Mean is :", x)

Mean is : 3


# Min

In [46]:
# Print the minimum number of a list.

a = (100,10,20,24,11,15,29,33,7,55)
x = min(a)
print(x)

7


# Maximum

In [47]:
# Print the maximum number of a list.

a = (100,10,20,24,11,15,29,33,7,55)
x = max(a)
print(x)

100


# Standard Deviation

In [48]:
# Calculates the Stand Deviation of a number´s list
import statistics

print(statistics.stdev([1,3,5,7,9,11]))

3.7416573867739413


# Median

In [49]:
# Get the median from a number´s list

import numpy

speed = [99,120,140,50,60,200,180]

x = numpy.median(speed)

print (x)

120.0


# TASK 4

## END